version: '2'
services:
  web:
    build: .
    image: alexanderlee/stone-soup:latest
    environment:
      - NODE_ENV=production
    ports:
      - 80:4000
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.2
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
